--- 
- hosts: all 
  remote_user: ansible 
  tasks: 
  - name: Vérfifier que EPEL est activé 
    yum: 
      name: epel-release 
      state: present 
    become: True 
  - name: Vérfifier que libselinux-python est present 
    yum: 
      name: libselinux-python  
      state: present 
    become: True 
  - name: Vérfifier que libsemanage-python est present 
    yum: 
      name: libsemanage-python 
      state: present 
    become: True
  - name: Vérfifier que NTP est present 
    yum: 
      name: ntp 
      state: present 
    become: True 
  - name: Vérfifier que le timezone est positionné à UTC 
    file: 
      src: /usr/share/zoneinfo/WET 
      dest: /etc/localtime 
      state: link 
    become: True 
  - name: Vérfifier que le service NTP est lancé et est activé 
    service: 
      name: ntpd 
      state: started 
      enabled: True 
    become: True 
  - name: Vérfifier que FirewallD est present 
    yum: 
      name: firewalld 
      state: present 
    become: True 
  - name: Vérfifier que FirewallD est lancé 
    service: 
      name: firewalld 
      state: started 
      enabled: True
    become: True     
  - name: Vérfifier que SSH peut passer le firewall 
    firewalld: 
      service: ssh 
      state: enabled 
      permanent: True 
      immediate: True 
    become: True