---
- name: "This Is The PLAY Documentation: This PLAY Runs Some Modules On The Target Hosts"
  hosts: webservers
  become: yes

  tasks:
  - name: "This Is The Task Documentation: This Task Executes The Group Module On Target Hosts"
    group:
      name: sysadmins
      state: present

  - name: "This Is The Task Documentation: This Task Executes The Group Module On Target Hosts"
    group:
      name: developpers
      state: present

  - name: "This Is The Task Documentation: This Task Executes The Group Module On Target Hosts"
    group:
      name: wheel
      state: present

  - name: "This Is The Task Documentation: This Task Creates Users On Target Hosts"
    user:
      name: developper1
      group: developpers
      groups: sysadmins
      password: $6$nn8ko7wO$5CgwCTjhNUwugB3QqElkn1gstgWhpDsJTD2Iiyg1VVCOEp5UoFjYc9bh85RCZ1HL2rA5Ogv0/eulu4gbpTw5D.
      state: present
  - name: "This Is The Task Documentation: This Task Creates Users On Target Hosts"
    user:
      name: developper2
      group: developpers
      password: $6$woGc.X2wfOlD3$z.zxCiMB.2toTQp9a34ss7L77curGesVYDFv7tvQI7f2cOKc9KH1FDkuQDr9OCYyS0fsaU/AktlhPujOrKHHb/
      state: present
  - name: "This Is The Task Documentation: This Task Creates Users On Target Hosts"
    user:
      name: automatic
      group: wheel
      state: present
