---
- name: "Include {{ ansible_os_family }}.yaml"
  include: "{{ ansible_os_family }}.yaml"

#- include: Debian.yaml
#  when: ansible_os_family == "Debian"
#- include: RedHat.yaml
#  when: ansible_os_family == "RedHat"
