---
- name: "PLAY de création de l'utilisateur technique ansible'"
  hosts: all
  remote_user: user
  become: yes
  gather_facts: false
  roles:
  - role: create-automation-user

- name: "PLAY de création de la base des données"
  hosts: database
  remote_user: ansible
  become: yes
  gather_facts: false
  tags: database  
  roles:
  - role: common
    tags: common  
  - role: database

- name: "PLAY de création du serveur web"
  hosts: webservers
  remote_user: ansible
  become: yes
  gather_facts: false
  tags: webservers  
  roles:
  - role: common
    tags: common
  - role: webserver

- name: "PLAY de création de l'application web"
  remote_user: ansible
  hosts: webservers
  tags: webapp
  roles:
  - role: webapp