---
# tasks file for roles/webapp
- name: Vérifier que le site web est présent et à jour 
  template: 
    src: index.html.j2 
    dest: /var/www/html/index.html
    owner: root
    group: root 
    mode: 0644 
  become: True
